MAX_THREADS: 4
RUN_MULTITHREADED: false
OUTPUT_DIR: "."
PARAMETERS_FOLDER: "../parameters"

COLLECTION_FOLDER: "../collections"
COLLECTION_FILE: "debug.yml"

#Logging
#Set the log level (levels: trace, debug, info, warn, error, critical)
LOG_LEVEL: "trace"
LOG_PATTERN: "[%Y-%m-%d %H:%M] [%l] %v"
LOG_TO_CONSOLE: true
LOG_TO_FILE: true
LOG_FILE: "debug.log"