MAX_THREADS: 48
RUN_MULTITHREADED: true
OUTPUT_DIR: ""
PARAMETERS_FOLDER: "../parameters"

COLLECTION_FOLDER: "../collections"
COLLECTION_FILE: "default_collection.yml"

#Logging
#Set the log level (levels: trace, debug, info, warn, error, critical)
LOG_LEVEL: "debug"
LOG_PATTERN: "[%Y-%m-%d %H:%M] [%l] %v"
LOG_TO_CONSOLE: true
LOG_TO_FILE: false
LOG_FILE: "debug.log"