

#ifndef GROUP_AUGMENTATION_ATTRIBUTE_H
#define GROUP_AUGMENTATION_ATTRIBUTE_H

enum Attribute {
    ALPHA, BETA, GAMMA, DELTA, DRIFT, DISPERSAL, HELP, SURVIVAL, AGE, AGE_BECOME_BREEDER

};

#endif //GROUP_AUGMENTATION_ATTRIBUTE_H
