

#ifndef GROUP_AUGMENTATION_ATTRIBUTE_H
#define GROUP_AUGMENTATION_ATTRIBUTE_H

enum Attribute {
    ALPHA, BETA, GAMMA, DELTA, DRIFT, DISPERSAL, JOIN_EMPTY_TERRITORY, HELP, SURVIVAL, AGE, AGE_BECOME_BREEDER, FECUNDITY

};

#endif //GROUP_AUGMENTATION_ATTRIBUTE_H
