#Run parameters
REACTION_NORM_HELP: false    # Apply reaction norm to age for level of help?
EVOLUTION_HELP_AFTER_DISPERSAL: false     # Help evolves only after the evolution of dispersal?
NO_GROUP_AUGMENTATION: false
NO_RELATEDNESS: false     # Apply implementation to remove the effect of relatedness?
AGE_NO_INFLUENCE_INHERITANCE: false # Age no influence of who inherits territory, randomly sampled from candidate (helpers + sample floaters)

MAX_COLONIES: 500     # max number of groups or colonies
NUM_GENERATIONS: 10000
MAX_NUM_REPLICATES: 1
SKIP: 1   # interval between print-outs

#Fix values
INIT_NUM_HELPERS: 3     # initial number of helpers per group
BIAS_FLOAT_BREEDER: 5  # mean of number of groups a floater can visit to try to become a breeder compared to 1 group for helpers
MIN_AGE_BECOME_BREEDER: 2 # minimum age for individuals to be able to become breeders, 1 is no restriction
FIXED_GROUP_SIZE: 3		# in implementation "no group augmentation", virtual group size used on survival formula

# Modifiers in survival
m: 0.2    # mortality due to predation
n: 1.2      # multiplier to m for lower mortality of floaters
X0: 1     # base survival without the effect of help or group size
Xh: 4    # cost of help in survival
Xn: 3    # benefit of group size in survival
Xe: 3    # cost of expulsion of immigrants in survival
Xrs: 5    # cost of reproductive supression in survival

#Modifiers in fecundity
K0: 1    # baseline fecundity when no other factors influence it
Kh: 0.5    # benefit of cumHelp in the fecundity
Kt: 0.1    # benefit of age in the fecundity
Knb: 2   # cost of number of breeders in the fecundity


#Genetic values

#For help
INIT_ALPHA: 0.0             #bigger values higher level of help
INIT_ALPHA_AGE: 0.0         #linear term for age, if 0 age has no effect
MUTATION_ALPHA: 0.05        # mutation rate in alpha for level of help
MUTATION_ALPHA_AGE: 0.05
STEP_ALPHA: 0.04            # mutation step size in alpha for level of help

#For dispersal
INIT_BETA: 1.0              # bigger values higher dispersal
MUTATION_BETA: 0.05         # mutation rate for the propensity to disperse
STEP_BETA: 0.1             # mutation step size for the propensity to disperse

#For expulsion of immigrants
INIT_GAMMA: 0.0              # bigger values higher expulsion
MUTATION_GAMMA: 0.05         # mutation rate for the expulsion effort
STEP_GAMMA: 0.1             # mutation step size for the expulsion effort

#For reproductive concessions
INIT_DELTA: 0.0             # bigger values higher reproductive share
MUTATION_DELTA: 0.05        # mutation rate in delta for level of reproductive share
STEP_DELTA: 0.04            # mutation step size in delta for level of reproductive share

#For relatedness
MUTATION_DRIFT: 0.05        # mutation rate in the neutral selected value to track level of relatedness
STEP_DRIFT: 0.04            # mutation step size in the neutral genetic value to track level of relatedness

