#Run parameters
REACTION_NORM_HELP: false    # Apply reaction norm to age for level of help?
EVOLUTION_HELP_AFTER_DISPERSAL: false     # Help evolves only after the evolution of dispersal?
NO_GROUP_AUGMENTATION: false
NO_RELATEDNESS: false     # Apply implementation to remove the effect of relatedness?
AGE_NO_INFLUENCE_INHERITANCE: false # Age no influence of who inherits territory, randomly sampled from candidate (helpers + sample floaters)

MAX_COLONIES: 1000     # max number of groups or colonies
NUM_GENERATIONS: 50000
MAX_NUM_REPLICATES: 2
SKIP: 500   # interval between print-outs

#Fix values
INIT_NUM_HELPERS: 3     # initial number of helpers per group
BIAS_FLOAT_BREEDER: 2  # mean of number of groups a floater can visit to try to become a breeder compared to 1 group for helpers
MIN_AGE_BECOME_BREEDER: 2 # minimum age for individuals to be able to become breeders, 1 is no restriction
FIXED_GROUP_SIZE: 3		# in implementation "no group augmentation", virtual group size used on survival formula

# Modifiers in survival
m: 0.2    # mortality due to predation
n: 1.2      # multiplier to m for lower mortality of floaters (only in the new logistic survival formula)
X0: 1.5   # base survival without the effect of help or group size
Xsh: 4    # cost of help in survival
Xsn: 3    # benefit of group size in survival
Xse: 0    # cost of expulsion of immigrants in survival

#Modifiers in fecundity
K0: 1    # min fecundity, fecundity when no help provided.
Kh: 1    # benefit of cumHelp in the fecundity


#Genetic values

#For help
INIT_ALPHA: 0.0             #bigger values higher level of help
INIT_ALPHA_AGE: 0.0         #linear term for age, if 0 age has no effect
MUTATION_ALPHA: 0.05        # mutation rate in alpha for level of help
MUTATION_ALPHA_AGE: 0.05
STEP_ALPHA: 0.04            # mutation step size in alpha for level of help

#For dispersal
INIT_BETA: 0.0              # bigger values higher dispersal
MUTATION_BETA: 0.05         # mutation rate for the propensity to disperse
STEP_BETA: 0.1             # mutation step size for the propensity to disperse

#For expulsion of immigrants
INIT_GAMMA: 0.0              #
MUTATION_GAMMA: 0.05         #
STEP_GAMMA: 0.04             #

#For reproductive concessions
INIT_DELTA: 0.0             #
MUTATION_DELTA: 0.05         # mutation rate in delta for level of help

#For relatedness
MUTATION_DRIFT: 0.05        # mutation rate in the neutral selected value to track level of relatedness
STEP_DRIFT: 0.04            # mutation step size in the neutral genetic value to track level of relatedness

